#!/bin/sh

set -e

GIT_EMAIL=""
GIT_USERNAME=""
LOG="no"

if [ -z "$1" ]; then
  GIT_USERNAME="Github Actions Bot"
else
  GIT_USERNAME="$1"
fi

if [ -z "$2" ]; then
  GIT_EMAIL="githubactionbot@gmail.com"
else
  GIT_EMAIL="$2"
fi

if [ -z "$3" ]; then
  LOG="no"
else
  LOG="$2"
fi

git config user.email "$GIT_EMAIL"
git config user.name "$GIT_USERNAME"

if [ "$LOG" != "no" ]; then
  echo "###[group] 🗃 Git Config"
  echo "  > Name  : $GIT_USERNAME"
  echo "  > Email : $GIT_EMAIL"
  echo "###[endgroup]"
fi
