#!/bin/sh

set -e

GIT_EMAIL=""
GIT_USERNAME=""

if [ -z "$1" ]; then
  GIT_USERNAME="Github Actions Bot"
else
  GIT_USERNAME="$1"
fi

if [ -z "$2" ]; then
  GIT_EMAIL="githubactionbot@gmail.com"
else
  GIT_EMAIL="$2"
fi

git config --global user.email "$GIT_EMAIL"
git config --global user.name "$GIT_USERNAME"

echo "###[group] 🗃 Git Config"
echo "  > Name  : $GIT_USERNAME"
echo "  > Email : $GIT_EMAIL"
echo "###[endgroup]"